name: RT-Thread_Packages_Test

on:
  [push, pull_request]

jobs:
  pkgs-test:
    uses: vacabun/pkgs-test/.github/workflows/pkgs-action.yml@del_rtthread_config_input
    with:
      pkgs-test-repository: vacabun/pkgs-test
      pkgs-test-branch: del_rtthread_config_input
      rt-thread-versions: branch:master tag:v5.0.0
      package-version: latest v2.0.4 v2.0.3 v2.0.2 v2.0.1
      
