name: RT-Thread_Packages_Test

on:
  [push, pull_request]

jobs:
  pkgs-test:
    uses: vacabun/pkgs-test/.github/workflows/pkgs-action.yml@main
    with:
      pkgs-test-repository: vacabun/pkgs-test
      pkgs-test-branch: main
      build-config: CONFIG_AT_USING_SOCKET=y
      package-version: latest
      
